package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.CourseLecturer;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CourseLecturerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE_LECTURER
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE_LECTURER
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    int insert(CourseLecturer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE_LECTURER
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    CourseLecturer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE_LECTURER
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    List<CourseLecturer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE_LECTURER
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    int updateByPrimaryKey(CourseLecturer record);
}