package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Faculty;
import org.mybatis.cdi.Mapper;

@Mapper
public interface FacultyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FACULTY
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FACULTY
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    int insert(Faculty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FACULTY
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    Faculty selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FACULTY
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    List<Faculty> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FACULTY
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    int updateByPrimaryKey(Faculty record);
}