package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.StudyProgramme;
import org.mybatis.cdi.Mapper;

@Mapper
public interface StudyProgrammeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDY_PROGRAMME
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDY_PROGRAMME
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    int insert(StudyProgramme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDY_PROGRAMME
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    StudyProgramme selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDY_PROGRAMME
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    List<StudyProgramme> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDY_PROGRAMME
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    int updateByPrimaryKey(StudyProgramme record);
}