package lt.vu.mybatis.model;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.ID
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.CREDITS
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    private Integer credits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.NAME
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.STUDY_PROGRAMME_ID
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    private Integer studyProgrammeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.ID
     *
     * @return the value of PUBLIC.COURSE.ID
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.ID
     *
     * @param id the value for PUBLIC.COURSE.ID
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.CREDITS
     *
     * @return the value of PUBLIC.COURSE.CREDITS
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public Integer getCredits() {
        return credits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.CREDITS
     *
     * @param credits the value for PUBLIC.COURSE.CREDITS
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public void setCredits(Integer credits) {
        this.credits = credits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.NAME
     *
     * @return the value of PUBLIC.COURSE.NAME
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.NAME
     *
     * @param name the value for PUBLIC.COURSE.NAME
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.STUDY_PROGRAMME_ID
     *
     * @return the value of PUBLIC.COURSE.STUDY_PROGRAMME_ID
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public Integer getStudyProgrammeId() {
        return studyProgrammeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.STUDY_PROGRAMME_ID
     *
     * @param studyProgrammeId the value for PUBLIC.COURSE.STUDY_PROGRAMME_ID
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public void setStudyProgrammeId(Integer studyProgrammeId) {
        this.studyProgrammeId = studyProgrammeId;
    }
}