package lt.vu.mybatis.model;

public class CourseLecturer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE_LECTURER.ID
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE_LECTURER.COURSE_ID
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE_LECTURER.LECTURER_ID
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    private Integer lecturerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE_LECTURER.ID
     *
     * @return the value of PUBLIC.COURSE_LECTURER.ID
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE_LECTURER.ID
     *
     * @param id the value for PUBLIC.COURSE_LECTURER.ID
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE_LECTURER.COURSE_ID
     *
     * @return the value of PUBLIC.COURSE_LECTURER.COURSE_ID
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE_LECTURER.COURSE_ID
     *
     * @param courseId the value for PUBLIC.COURSE_LECTURER.COURSE_ID
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE_LECTURER.LECTURER_ID
     *
     * @return the value of PUBLIC.COURSE_LECTURER.LECTURER_ID
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public Integer getLecturerId() {
        return lecturerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE_LECTURER.LECTURER_ID
     *
     * @param lecturerId the value for PUBLIC.COURSE_LECTURER.LECTURER_ID
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public void setLecturerId(Integer lecturerId) {
        this.lecturerId = lecturerId;
    }
}