package lt.vu.mybatis.model;

public class StudyProgramme {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDY_PROGRAMME.ID
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDY_PROGRAMME.NAME
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDY_PROGRAMME.FACULTY_ID
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    private Integer facultyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDY_PROGRAMME.ID
     *
     * @return the value of PUBLIC.STUDY_PROGRAMME.ID
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDY_PROGRAMME.ID
     *
     * @param id the value for PUBLIC.STUDY_PROGRAMME.ID
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDY_PROGRAMME.NAME
     *
     * @return the value of PUBLIC.STUDY_PROGRAMME.NAME
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDY_PROGRAMME.NAME
     *
     * @param name the value for PUBLIC.STUDY_PROGRAMME.NAME
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDY_PROGRAMME.FACULTY_ID
     *
     * @return the value of PUBLIC.STUDY_PROGRAMME.FACULTY_ID
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public Integer getFacultyId() {
        return facultyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDY_PROGRAMME.FACULTY_ID
     *
     * @param facultyId the value for PUBLIC.STUDY_PROGRAMME.FACULTY_ID
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public void setFacultyId(Integer facultyId) {
        this.facultyId = facultyId;
    }
}