package lt.vu.mybatis.model;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.ID
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.NAME
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.SURNAME
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    private String surname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.START_YEAR
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    private Integer startYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.STUDY_PROGRAMME_ID
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    private Integer studyProgrammeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.ID
     *
     * @return the value of PUBLIC.STUDENT.ID
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.ID
     *
     * @param id the value for PUBLIC.STUDENT.ID
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.NAME
     *
     * @return the value of PUBLIC.STUDENT.NAME
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.NAME
     *
     * @param name the value for PUBLIC.STUDENT.NAME
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.SURNAME
     *
     * @return the value of PUBLIC.STUDENT.SURNAME
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.SURNAME
     *
     * @param surname the value for PUBLIC.STUDENT.SURNAME
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.START_YEAR
     *
     * @return the value of PUBLIC.STUDENT.START_YEAR
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public Integer getStartYear() {
        return startYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.START_YEAR
     *
     * @param startYear the value for PUBLIC.STUDENT.START_YEAR
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public void setStartYear(Integer startYear) {
        this.startYear = startYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.STUDY_PROGRAMME_ID
     *
     * @return the value of PUBLIC.STUDENT.STUDY_PROGRAMME_ID
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public Integer getStudyProgrammeId() {
        return studyProgrammeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.STUDY_PROGRAMME_ID
     *
     * @param studyProgrammeId the value for PUBLIC.STUDENT.STUDY_PROGRAMME_ID
     *
     * @mbg.generated Wed May 03 03:45:09 EEST 2023
     */
    public void setStudyProgrammeId(Integer studyProgrammeId) {
        this.studyProgrammeId = studyProgrammeId;
    }
}